### PR TITLE
fix only enabling shortcuts if body has focus

### LINKED ISSUE #104: bug: hitting space bar while typing into search bar activates keyboard shortcut to play/pause instead
When typing into the search bar, when a user adds a space for, say, multiple search terms, that activates the keyboard shortcut to pause the sound if it's playing or play the sound if it isn't. In addition, the space will not show up in the search bar.

I think looking at some of the changes in #66 and #85 might be helpful.

### PR DESCRIPTION
**Pull request by hamirmahal**
This tries to fix #104 by checking if the `<body>` is the `document.activeElement` before allowing use of the keyboard shortcuts we previously added.

### CODE REVIEW

File: src/Sound.js [hunk 1]
```diff
@@ -87,20 +87,22 @@ export default function Sound(props) {
...
-        setIsPlaying((i) => !i);
-      },
-      d: () => {
-        if (isLoggedIn) downloadSound(sound);
-      },
-    });
-    return () => {
-      unsubscribe();
-    };
+    if (document.activeElement.id === "body") {
```
Comment (amilajack) [inline src/Sound.js:92]: no need to have an id here. There should only be one body. What you could do is check for reference equality: `document.activeElement === document.body`

**Review by amilajack — CHANGES_REQUESTED** [review]

File: src/Sound.js (hunk 1 above)
Comment (hamirmahal) [reply src/Sound.js:92]: Ah, I was not aware of that. Thanks for the tip!

File: src/Sound.js [hunk 2]
```diff
@@ -87,15 +87,17 @@ export default function Sound(props) {
     };
     fetchSound();
   }, [id, freeSound]);
-
   useEffect(() => {
     const unsubscribe = tinykeys(window, {
       Space: (event) => {
-        event.preventDefault();
-        setIsPlaying((i) => !i);
+        if (document.activeElement === document.body) {
```
Comment (amilajack) [inline src/Sound.js:93]: nit: we should probably add some comments here explaining the check we're performing here

**Review by amilajack — CHANGES_REQUESTED** [review]

File: src/Sound.js (hunk 2 above)
Comment (hamirmahal) [reply src/Sound.js:93]: For sure. I added a couple comments, as you'll see in the incoming commit.

File: src/Sound.js [hunk 3]
```diff
@@ -87,16 +87,20 @@ export default function Sound(props) {
     };
     fetchSound();
   }, [id, freeSound]);
-
   useEffect(() => {
     const unsubscribe = tinykeys(window, {
       Space: (event) => {
-        event.preventDefault();
```
Comment (amilajack) [inline src/Sound.js:94]: We should add this back

**Review by amilajack — CHANGES_REQUESTED** [review]

File: src/Sound.js (hunk 3 above)
Comment (hamirmahal) [reply src/Sound.js:94]: It's still here, on line 95.

**Review by amilajack — APPROVED** [review]
