### PR TITLE
fix: fix #212 by only rendering Pack <SoundList /> component if nonempty

### LINKED ISSUE #212: bug: no pack sounds shows empty list, looks awkward
We should not render the pack SoundList if there are no items in the pack:

Screen Shot 2020-11-19 at 9 02 21 PM

### PR DESCRIPTION
**Pull request by hamirmahal**
This pull request fixes #212 if we merge it. It fixes the issue of empty Pack <SoundList /> components displaying using the relatively straightforward approach of only displaying a Pack <SoundList /> component if `packSounds` has a first element, i.e., if `packSounds` is not empty.﻿

### CODE REVIEW

**Comment by hamirmahal** [comment]
To get a visual for what this pull request does, notice how the current version of our application at https://freesound-player.vercel.app/sound/396855 displays the "Pack" header even if `packSounds` is empty, as @amilajack mentioned in #212.

Screen Shot 2020-11-20 at 1 12 09 PM

The same sound at https://freesound-player-git-fix-empty-pack-soundlist.amilajack.vercel.app/sound/396855, the version of our application with the changes from this pull request, does not display the "Pack" header, since there are no additional pack sounds that come with this one.

Screen Shot 2020-11-20 at 1 12 48 PM

File: src/Sound.js [hunk 1]
```diff
@@ -180,14 +180,16 @@ export default function Sound(props) {
...
       )}
-      <SoundList
-        header="Pack"
-        tracks={packSounds}
-        selectedTrack={sound?.id || packSounds[0]?.id || 0}
-        setSelectedTrack={() => {}}
-        onSoundClick={() => window.scrollTo(0, 0)}
-        className="pb-16"
-      />
+      {packSounds[0] && (
```
Comment (amilajack) [inline src/Sound.js:183]: nit: we could do `packSounds.length && ...`. This is more idiomatic in JS since `0` is falsy.
```suggestion
      {packSounds.length && (
```

**Review by amilajack — CHANGES_REQUESTED** [review]

File: src/Sound.js (hunk 1 above)
Comment (hamirmahal) [reply src/Sound.js]: Oh! So, if `packSounds[0]` has a falsy value, the "Pack" `<SoundList />` could still not render, even though it's not empty?

Comment (hamirmahal) [reply src/Sound.js]: It appears that if `packSounds` is empty, like in https://freesound-player.vercel.app/sound/396855, the application displays `packSounds.length`, which would be `0` in this case, onscreen where the Pack `<SoundList />` component would be if `packSounds` was nonempty.

It works fine for packs that are not empty, though, like https://freesound-player.vercel.app/sound/376626. The issue persists across both Chrome and Safari.

Screen Shot of sound with empty pack at 2020-11-20 at 6 55 16 PM

Screen Shot of sound with nonempty pack at 2020-11-20 at 6 56 34 PM

It works perfectly fine if we change [lines 183 though lines 192 of the latest commit at the time of this writing](https://github.com/amilajack/freesound-player/blob/e1bfac95ed48a042997dafa12233bd9ae3067755/src/Sound.js#L183) to

```
      {packSounds.length ? (
        <SoundList
          tracks={packSounds}
          selectedTrack={sound?.id || packSounds[0]?.id || 0}
          setSelectedTrack={() => {}}
          onSoundClick={() => window.scrollTo(0, 0)}
          header="Pack"
          className="pb-16"
        />
      ) : (
        <></>
      )}
```

but I'm wondering if the original approach would just be cleaner. What are your thoughts?

**Comment by amilajack** [comment]
Thanks for calling this out! Fixed this in a recent forced push to master.

**Comment by hamirmahal** [comment]
You're welcome! I saw the new commit after doing `git fetch`. It looks like it's working well: https://freesound-player.vercel.app/sound/396855 doesn't display `packSounds.length` on screen anymore. Happy to help!

Screen Shot 2020-11-20 at 7 46 42 PM
