### PR TITLE
fix broken layout of list icons

### LINKED ISSUE #186: fix broken layout of list icons

### PR DESCRIPTION
**Pull request by akshara-sun**
closes #186

### CODE REVIEW

**Review by amilajack — CHANGES_REQUESTED** [review]
Bug 🐛 on smaller viewports
Screen Shot 2020-11-18 at 5 05 21 PM

File: src/SoundList.js [hunk 1]
```diff
@@ -32,13 +32,23 @@ const SoundList = ({ tracks, header, onSoundClick, className = "" }) => {
...
-                <IonIcon className="pr-4" icon={downloadSharp} size="large" />
-                {track.num_downloads}
-                <IonIcon className="pr-4" icon={playCircleSharp} size="large" />
-                {track.num_ratings}
+              <div className="w-6/12 hidden sm:flex flex-row justify-end items-center opacity-50 group-hover:opacity-100 sm:hover:opacity-0">
+                <div className="flex justify-start w-2/12 items-center">
+                  <IonIcon className="p-2" icon={timeSharp} size="large" />
+                  {timeConvert(track.duration)}
+                </div>
+                <div className="flex justify-start w-2/12 items-center">
```
Comment (amilajack) [inline src/SoundList.js:40]: use `justify-end` instead of `justify-start`

File: src/SoundList.js [hunk 2]
```diff
@@ -32,13 +32,23 @@ const SoundList = ({ tracks, header, onSoundClick, className = "" }) => {
...
               </div>
-              <div className="hidden sm:flex flex-row justify-end items-center opacity-50 group-hover:opacity-100 sm:hover:opacity-0 space-x-12">
-                <IonIcon className="pr-4" icon={timeSharp} size="large" />
-                {timeConvert(track.duration)}
-                <IonIcon className="pr-4" icon={downloadSharp} size="large" />
-                {track.num_downloads}
-                <IonIcon className="pr-4" icon={playCircleSharp} size="large" />
-                {track.num_ratings}
+              <div className="w-6/12 hidden sm:flex flex-row justify-end items-center opacity-50 group-hover:opacity-100 sm:hover:opacity-0">
+                <div className="flex justify-start w-2/12 items-center">
```
Comment (amilajack) [inline src/SoundList.js:36]: Change `w-2/12` to `w-4/12`

File: src/SoundList.js [hunk 3]
```diff
@@ -32,13 +32,23 @@ const SoundList = ({ tracks, header, onSoundClick, className = "" }) => {
...
                 </span>
               </div>
-              <div className="hidden sm:flex flex-row justify-end items-center opacity-50 group-hover:opacity-100 sm:hover:opacity-0 space-x-12">
-                <IonIcon className="pr-4" icon={timeSharp} size="large" />
-                {timeConvert(track.duration)}
-                <IonIcon className="pr-4" icon={downloadSharp} size="large" />
-                {track.num_downloads}
-                <IonIcon className="pr-4" icon={playCircleSharp} size="large" />
-                {track.num_ratings}
+              <div className="w-6/12 hidden sm:flex flex-row justify-end items-center opacity-50 group-hover:opacity-100 sm:hover:opacity-0">
```
Comment (amilajack) [inline src/SoundList.js:35]: Try `w-6/12 md:w-4/12 md:space-2`

File: src/SoundList.js [hunk 4]
```diff
@@ -32,13 +32,23 @@ const SoundList = ({ tracks, header, onSoundClick, className = "" }) => {
                   {track.username}
```
Comment (amilajack) [inline src/SoundList.js:32]: suggestion: remove `pr-12` class from code above

File: src/SoundList.js [hunk 5]
```diff
@@ -32,13 +32,23 @@ const SoundList = ({ tracks, header, onSoundClick, className = "" }) => {
...
+                <div className="flex justify-start w-2/12 items-center">
+                  <IonIcon className="p-2" icon={timeSharp} size="large" />
+                  {timeConvert(track.duration)}
+                </div>
+                <div className="flex justify-start w-2/12 items-center">
+                  <IonIcon className="p-2" icon={downloadSharp} size="large" />
+                  {track.num_downloads}
+                </div>
+                <div className="flex justify-start w-2/12 items-center">
+                  <IonIcon
```
Comment (amilajack) [inline src/SoundList.js:45]: To fix shrinking buttons issue, try this:

```js
<IonIcon ... />
<span class="m-1">{track.num_ratings}</span>
```

**Review by amilajack — CHANGES_REQUESTED** [review]

**Comment by amilajack** [comment]
This is what i see after applying the suggestions above
Screen Shot 2020-11-18 at 5 21 11 PM
Screen Shot 2020-11-18 at 5 21 24 PM

File: src/SoundList.js (hunk 1 above)
Comment (akshara-sun) [reply src/SoundList.js:40]: The only reason I used justify-start instead of justify end is because it made the first two columns very crowded looking. Let me go back and try again, thanks for the tip.

File: src/SoundList.js (hunk 2 above)
Comment (akshara-sun) [reply src/SoundList.js:36]: I tried that but then they're too far apart, I am trying to make them to look as close to the Figma as possible.

**Comment by akshara-sun** [comment]
@amilajack  I made all the changes you suggested and noticed that the position of the icons become uneven anytime we have a number that has more than 2 or 3 digits. 

Side note: I did not remove` pr-12 ` from line 23 like you suggested because when I did, the layout ended up looking like this:
Screen Shot 2020-11-18 at 8 10 24 PM

Also, I know what caused the merge conflicts so I can fix that after you review the new changes.

File: src/SoundList.js [hunk 6]
```diff
@@ -32,13 +32,23 @@ const SoundList = ({ tracks, header, onSoundClick, className = "" }) => {
...
-                <IonIcon className="pr-4" icon={downloadSharp} size="large" />
-                {track.num_downloads}
-                <IonIcon className="pr-4" icon={playCircleSharp} size="large" />
-                {track.num_ratings}
+              <div className="w-6/12 md:w-4/12 md:space-2 hidden sm:flex flex-row justify-end items-center opacity-50 group-hover:opacity-100 sm:hover:opacity-0">
+                <div className="flex justify-end w-4/12 items-center">
+                  <IonIcon className="p-2" icon={timeSharp} size="large" />
+                  {timeConvert(track.duration)}
+                </div>
+                <div className="flex justify-end w-4/12 items-center">
```
Comment (amilajack) [inline src/SoundList.js:40]: we should revert the change to justify-end and i think we can merge this

**Review by amilajack — CHANGES_REQUESTED** [review]

File: src/SoundList.js (hunk 1 above)
Comment (hamirmahal) [reply src/SoundList.js]: > use `justify-end` instead of `justify-start`

Since I initially wasn't familiar with what either of these do, I read up on them. I'll share what I read in case it helps anyone reading this thread in the future.

[Tailwind's Justify Content documentation](https://tailwindcss.com/docs/justify-content) says that `justify-start` is shorthand for `justify-content: flex-start;` and `justify-end` is shorthand for `justify-content: flex-end;`.

Since [`justify-content: flex-start;` makes flex items "packed toward the start line" and `justify-content: flex-end;` makes items "packed toward to end line"](https://css-tricks.com/almanac/properties/j/justify-content/), using `justify-end` instead of `justify-start` would make flex items pack toward the end of the main axis instead of toward the start.

I found the below graphic from https://css-tricks.com/snippets/css/a-guide-to-flexbox/ really helpful.

Screen Shot of graphic from https://css-tricks.com/snippets/css/a-guide-to-flexbox/ at 2020-11-18 at 8 59 16 PM

Hope it helps!

File: src/SoundList.js (hunk 6 above)
Comment (akshara-sun) [reply src/SoundList.js:40]: what do you mean by revert? It is currently `justify-end
`

Comment (akshara-sun) [reply src/SoundList.js:40]: do you mean revert it back to `justify-start`?

Comment (amilajack) [reply src/SoundList.js:40]: yes

**Comment by amilajack** [comment]
Icons are still broken on smaller viewports. @akshara-sun can you please file a bug for this. Its not very high priority as other issues so we can take a look later.

Screen Shot 2020-11-19 at 9 24 48 PM

**Review by amilajack — APPROVED** [review]

**Comment by akshara-sun** [comment]
@amilajack I will file a bug, thanks.
